apiVersion: v1
kind: ServiceAccount
metadata:
  name: satest
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: satest-token
  annotations:
    kubernetes.io/service-account.name: satest
type: kubernetes.io/service-account-token
